# Project: bank_vector
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = hamxuly.o main.o
LINKOBJ  = hamxuly.o main.o
LIBS     = -L"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/include" -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Downloads/app code/Dev c++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = bank_vector.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Downloads\app code\Dev c++\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

hamxuly.o: hamxuly.cpp
	$(CPP) -c hamxuly.cpp -o hamxuly.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
